### ISSUE TITLE
User Password

### ISSUE THREAD

**Issue by arnon001** [adithyapaib/ubunturdp#2]
Hello!,
what is the User Password For The Root User in the rdp?

**Comment by adithyapaib** [comment]
123456

**Comment by arnon001** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/58848496/125120379-0ded4a00-e0fb-11eb-98dd-68e73cdd3aaa.png)
Doesn't Works, (Yes, i have windows 11)

**Comment by adithyapaib** [comment]
root has no password just click enter
